imports = ["feeds.toml", "music.toml"]

[[show]]
title = "The Half-Assed Show"
description = "It aint perfect, but it works"
interlude = true
timetable = [ "-t casual funny", "-t storytelling", "-t news", "-t news", "-t talk", "-t funny", "-t storytelling", "-t documentaries"]